docs/sim/index.rst, urbansim/sim/simulation.py, urbansim/sim/tests/test_simulation.py
This enables something like this:
```python
@sim.injectable(autocall=False, memoize=True)
def my_utility_func(x, y, z):
return x + y + z
@sim.column()
def my_col(another_col, my_utility_func):
result = my_utility_func(1, 2, 3)
return another_col * result
```
And if you call `my_utility_func` again with the input of `1, 2, 3` you'll get back the cached result instead of re-doing the calculation.
Memoization requires `autocall=False` and that function inputs always be hashable. The memoization cache follows the same rules as other caching, so you can use `cache_scope=`, `sim.clear_cache`, `sim.disable_cache`, and `sim.enable_cache` as usual.
=> Injectable Memoization

urbansim/accounts.py, urbansim/models/tests/test_regression.py, urbansim/sim/tests/test_simulation.py
pep8 apparently doesn't like it if you assign a lambda function
to a variable, things you should define the function using a def.
=> Turn some lambdas into defs

urbansim/developer/sqftproforma.py, urbansim/models/__init__.py, urbansim/models/dcm.py, urbansim/models/tests/test_dcm.py, urbansim/urbanchoice/interaction.py, urbansim/urbanchoice/tests/test_interaction.py
This is a big set of changes associated with synthicity/activitysim#3.
The goal here is to generalize our existing location choice model classes into discrete choice models with varying capabilities. The LCMs had baked in some assumptions that made them inappropriate for something like automobile ownership, even though the underlying MNL code is fully compatible with general discrete choice modeling. These some of the assumptions:
- only one chooser was used for calculating probabilites
- choices were made for choosers in aggregate because all choosers had the same probabilities, locations are unavailable once chosen, and it results in better performance
- locations were removed from the alternatives pool at the group level because those locations were no longer available to others once …
=> Discrete Choice Models

urbansim/models/dcm.py, urbansim/models/tests/test_dcm.py
Someone might create a `SegmentedMNLDiscreteChoiceModel` via yaml
with non-default probability and choice modes and those
were not being passed down to the models for individual segments.
=> Have seg models pass prob & choice mode to ind models

urbansim/models/dcm.py, urbansim/models/tests/test_dcm.py, urbansim/urbanchoice/interaction.py, urbansim/utils/yamlio.py
It's kind of limited sampling, not something you could use
during a location choice model. Alternatives may show up as
available for more than one chooser and alternatives may show up
more than once for a single chooser.
=> Allow sampling of alternatives during prediction

urbansim/models/dcm.py, urbansim/models/tests/test_dcm.py
We weren't removing the choosers layer of the summed probs MultiIndex when `probability_mode='single_chooser'`, so the summed probs in that mode would have a weird MultiIndex.
Fixed it to drop the chooser ID layer of the summed probs index when in "single chooser" mode.
=> Make sure summed probs indexes match alts

urbansim/models/tests/test_dcm.py, urbansim/urbanchoice/interaction.py
This addresses https://github.com/UDST/bayarea_urbansim/issues/65 by reverting https://github.com/UDST/urbansim/commit/d17a5ced1aca84e9e0fce0249921255804d51a52. That change was made to ensure that choosers weren't being given the opportunity to choose the same alternative multiple times, but performance is very bad with `np.random.choice` being called many tens of thousands of times. In most UrbanSim LCM applications the pool of available alternatives is much larger than the alternative sample size so we don't worry too much about repeated sampling, but it could be a problem in other contexts.
One possible solution allowing us to do individual sampling would be to use the Python standard library's `random.sample`, which is much, much faster than `np.random.choice`. The downside of that …
=> Revert Alternative Sampling

urbansim/developer/developer.py, urbansim/developer/sqftproforma.py, urbansim/developer/tests/test_sqftproforma.py
most of this commit is to make sure we account for the amount of a building that is parking and the amount that is not when crediting rents for the building.
the old structure of the pro forma was to maxmize the parking format (surface, deck, underground) in the precomputation part of the pro forma.  now this is put off until actual rents and costs are known.  this allows more flexibility in how the comutation is done.
in this case it actually removed a bug where we were giving too much rent for space that is actually only devoting to parking, which made itself known in the simulations as redeveloping sururban office developments that had surface parking and turning them into dense deck parking office developments because although the cost of the parking was taken into account, it was …
=> fixed a problem with deck parking in the developer

urbansim/models/tests/test_transition.py, urbansim/models/transition.py
* return `pd.DataFrame` with `pd.Int64Index()` index in `remove_rows()`
* add `assert_empty_int64index()` to use with `test_tgrtransition_with_accounting()`
I tried changing as little code as possible.
Note that the failed build is due to changes in pandas (possibly 0.18 (or >=0.17.1)), as commented [here](https://github.com/UDST/urbansim/commit/058a930f31cd9c9c4d16c1875578f3c66086cc3f#commitcomment-16666541).
--
Alternatively, for the `test_*remove*all()` tests at least, the `check_index_type` option in `pdt.assert_frame_equal()` can be set to `False`. This isn't guaranteed to fix everything.
=> use `pd.Int64Index()`

urbansim/developer/developer.py
When you merge the old buildings and the new buildings, you actually change the buildings ids of the new buildings in order to maintain uniqueness fo the index.  Settings this flag returns the new index in case the user needs it (which is not always the case).
=> return index after dev.merge

urbansim/developer/developer.py
Taking the comment from the code:
+            As there are so many ways to turn the development feasibility
+            into a probability to select it for building, the user may pass
+            a function which takes the feasibility dataframe and returns
+            a series of probabilities.  If no function is passed, the behavior
+            of this method will not change
This actually replaces the return-on-cost branch.  Instead of trying to come up with the "correct" profit to probability mapping, I've added the ability to pass in a function so that the user can specify that mapping.  The current way of doing this will remain unchanged so this in no way changes the default behavior of UrbanSim.  I will close and delete the return-on-cost branch since it's unneeded at this …
=> General profit to prob

urbansim/models/dcm.py
Currently, in the MNLDiscreteChoiceModel and SegmentedMNLDiscreteChoiceModel classes, the predict_from_cfg helper function defaults to using from_yaml by passing a file path string. However, from_yaml includes a yaml_str option that allows for passing the config in from memory as a yaml string. This change allows for passing a yaml config string from memory into predict_from_cfg, which is useful in the case that configurations need to be edited within a model and an lcm run based on those edited configs (and where you don't really want to save out the yaml file).
=> pass yaml str from memory to predict_from_cfg

urbansim/developer/developer.py
If feasibility for all buildings of a given form is n/a, developer.pick raises a ValueError exception.
check of dataframe length implemented
=> bugfix for issue #174:

urbansim/utils/sampling.py, urbansim/utils/tests/test_sampling.py
This addresses feedback when the accounting total is not met (#178) and also providing probability distributions to influence the sample (#149).
To obtain feedback, set the return_status argument to True, and this will return both the sampled rows and the status. If False, then only the sampled rows will be returned. This is still the default, so as to not break any existing calls. 
To provide sampling probabilities, set the prob_column argument to the name of the column in the data frame containing the weights or probabilities. These values will be normalized so they sum to 1, if they do not already.  
The logic for sampling with accounting but without replacement has been changed to hopefully be more robust.
=> Fix sample rows no replace

urbansim/models/dcm.py
Running a standard parcel model with numpy 1.12 installed hits a `TypeError` in the `predict_from_cfg` method of the segmented DCM (this also affects the base MNL DCM as well). See traceback:
```
File "/Users/paulsohn/Documents/sanfran_urbansim/models.py", line 47, in hlcm_simulate
"vacant_residential_units")
File "/Users/paulsohn/Documents/sanfran_urbansim/utils.py", line 191, in lcm_simulate
new_units, _ = yaml_to_class(cfg).predict_from_cfg(movers, units, cfg)
File "/Users/paulsohn/anaconda2/lib/python2.7/site-packages/urbansim-3.1.dev0-py2.7.egg/urbansim/models/dcm.py", line 1852, in predict_from_cfg
replace=False)
File "mtrand.pyx", line 1176, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:18822)
TypeError: 'numpy.float64' object cannot be interpreted as an index
``` …
=> Fix type error in predict_from_cfg methods in DCM

urbansim/urbanchoice/tests/test_mnl.py, urbansim/utils/sampling.py
This is an extension to #182. Numpy 1.12 raises a `TypeError` when floats are passed to a parameter that wants an integer in two places that interact with urbansim:
* The `size` parameter in [numpy.random.choice](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.choice.html)
* The `newshape` parameter in [numpy.reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)
These two issues have been fixed in a couple of places by simply casting to int again.
=> Two more TypeError fixes related to numpy 1.12

urbansim/models/tests/test_regression.py
Addresses #185. [Statsmodels 0.8](http://www.statsmodels.org/stable/release/version0.8.html), released in February, changes the behavior of the `predict()` method when a DataFrame is passed to the exog argument: it used to drop a row from the returned prediction column if any of the inputs for that row were nan, it now returns that row with nan. 
The new behavior is more intuitive than before, and since most urbansim models are probably set up to drop nans before passing to `predict()` anyway, we'll just change the unit test here to make sure the appropriate nan is returned.
=> Change regression.py unit test based on change in statsmodels 0.8

urbansim/models/dcm.py
I can't actually explain why, but this one tiny change speeds the simulation up 25 minutes for a 70 minutes simulation. 
There should be no behavior difference here - it just protects the case where there are no alternatives, which would return the same empty list you started with inside this loop.  I don't really understand why it would take so long, and in basic tests outside of UrbanSim I can't recreate it.  It seems like a harmless change though, so merging it to master seems innocuous.
=> merging in the UAL changes uncovered this performance issue in UrbanSim

docs/gettingstarted.rst, setup.py
Change required version of statsmodels in setup.py and in documentation, since old versions have different behavior in `predict()` method and are incompatible with new unit tests.
=> Bump statsmodels version number

urbansim/models/dcm.py
We protect against the boundary case of having no choosers in the predict method, but this gets circumvented and is still a problem with the supply and demand code.
I was hoping to protect against this outside of urbansim, but we don't know how many choosers there are until the predict_filters gets run, and that happens in urbansim.
=> fixed boundary case in supply and demand

.travis.yml, appveyor.yml, setup.py, urbansim/developer/developer.py, urbansim/developer/sqftproforma.py, urbansim/maps/dframe_explorer.py, urbansim/models/supplydemand.py, urbansim/models/tests/test_regression.py, urbansim/models/tests/test_transition.py, urbansim/models/tests/test_util.py, urbansim/models/transition.py, urbansim/models/util.py, urbansim/tests/test_accounts.py, urbansim/urbanchoice/interaction.py, urbansim/urbanchoice/mnl.py, urbansim/urbanchoice/pmat.py, urbansim/utils/misc.py, urbansim/utils/networks.py, urbansim/utils/testing.py, urbansim/utils/tests/test_misc.py, urbansim/utils/tests/test_sampling.py, urbansim/utils/tests/test_testing.py, urbansim/utils/tests/test_yamlio.py, urbansim/utils/yamlio.py
This PR includes many changes to make UrbanSim compatible with both Python 2.7 and 3.X. Changes include (in order of importance):
* Added future import of true division and forced floor division in a few places where it seemed necessary, mostly `mnl.py` and `pmat.py`. @fscottfoti it would be great if you wouldn't mind taking a look at these (I added TODOs in the important spots).
* Changes to iterators like `dict.iteritems()` and `itertools.izip()` which were removed in Python 3. I replaced iteritems with `dict.items()` which is inefficient in Python 2 since it doesn't use a generator, but most use cases are very simple so it shouldn't make a different in performance.
* Convert implicit relative imports to explicit relative imports where appropriate.
* Error message strings in the …
=> Python 3 compatibility

urbansim/utils/misc.py, urbansim/utils/tests/test_misc.py
This PR adds a new method for re-indexing a series or data frame based on a foreign key relationship, called **_fidx_**. This is is similar to  _utils.misc.reindex_. The key differences are
1) This method can re-index both series and data frames.
2) The method can re-index using mutliple-columns on the left, this implies that the right has a multi-index. This is helpful when doing an aggregation across multiple columns and then joining the result back to the original data frame.
For example, suppose we want to assign to each household the number of households of the same building type in their zone:
```python
hh_by_zone_type = h.groupby(['zone', 'building_type_id']).size()
h['zonal_hh_same_type'] = fidx(hh_by_zone_type, h, ['zone', 'building_type_id'])
``` 
See the tests for examples.
=> add fidx and tests

urbansim/utils/tests/test_yamlio.py, urbansim/utils/yamlio.py
Currently, in _utils.yamlio_, dictionaries exported via _convert_to_yaml_ use a hard-coded list to control the ordering of keys in the output file. This has two drawbacks (1) the list has to be updated when new parameters are added and (2) only the outer dictionaries ordering can be controlled, the ordering of inner dictionaries will not follow the order list. 
This PR adds support for exporting ordered dictionaries to yaml in _utils.yamlio_.  For example, the following: 
```python
inner_dict = OrderedDict()
inner_dict['z'] = 'had'
inner_dict['a'] = 'a'
inner_dict['f'] = 'little'
outer_dict = OrderedDict()
outer_dict[10] = 'marry'
outer_dict['inner'] = inner_dict
outer_dict['a'] = 'lamb'
yamlio.convert_to_yaml(outer_dict, my_file.yaml)
```
Will have the following yaml:
```yaml
10: marry …
```
=> allow ordered dict export to yaml

urbansim/models/transition.py
remove_rows() was previously checking the number of units (hh, jobs, establishments) to remove against the number of rows in the data table rather than the sum of the accounting_column in that table and segment. This was causing a ValueError in cases where a lot of units in the accounting_column (e.g. establishments.employees) needed to be removed.
=> check nrows against accounting_column sum in transition remove_rows()

setup.py
If the latest version is used, we can end up with v0.4.0 that seems to
have issues with Travis.
=> Fixing pandana version to 0.3.0

urbansim/urbanchoice/mnl.py, urbansim/urbanchoice/pmat.py
At yesterday's meeting with @semcogli and @janowicz discuss how deeply **odd** our fitted mnl models wore. Specifically, we have variables that have to be positive that are being fit as negative. In the meeting we considered the possibility of collinearity, or spurious correlations, or bad sampling processes, or other complex possibilities. After the meating I thought that the simplest explanation would be if the optimization algorithm had not successfully `fitted` the models in the first place. 
Looking at the code I see that we did not check it `optimize.fmin_l_bfgs_b` had succeeded. So I added a warning that reports some diagnostic information in case of non-convergence. 
When I ran the tests I noted that `test_alternative_specific_coeffs` reliably thru a non-convergence warning …
=> worn in the case of non-convergence

.travis.yml, appveyor.yml, urbansim/models/dcm.py, urbansim/urbanchoice/tests/test_interaction.py, urbansim/urbanchoice/tests/test_mnl.py, urbansim/utils/misc.py, urbansim/utils/tests/test_testing.py
Make updates for new version of Pandas:
- Use `.reindex()` instead of `.loc` when there are missing values
- change `.as_matrix()` for `.values`
=> Compatibility with Pandas v1.0

urbansim/models/tests/test_dcm.py, urbansim/models/tests/test_regression.py, urbansim/utils/networks.py, urbansim/utils/tests/test_yamlio.py, urbansim/utils/yamlio.py
This PR resolves `yaml.load()` deprecations, as described in issue #216.
Replaces all instances of `yaml.load()` with `yaml.safe_load()`, except where a `Loader=...` argument is provided.
`yaml.safe_load()` prevents arbitrary Python data types from being encoded and decoded from yaml. Since our use case here is specifically to store dictionary representations of model specifications, I don't see this being an issue. 
See additional discussion in issue #216.
=> Resolve yaml.load() deprecations
